const gal1 = {
  0: require('../images/gallery/gal1/0.png'),
  1: require('../images/gallery/gal1/1.png'),
  2: require('../images/gallery/gal1/2.png'),
  3: require('../images/gallery/gal1/3.png'),
  4: require('../images/gallery/gal1/4.png'),
  5: require('../images/gallery/gal1/5.png'),
  6: require('../images/gallery/gal1/6.png'),
  7: require('../images/gallery/gal1/7.png'),
  8: require('../images/gallery/gal1/8.png'),
  9: require('../images/gallery/gal1/9.png'),
  10: require('../images/gallery/gal1/10.png'),
  11: require('../images/gallery/gal1/11.png'),
  12: require('../images/gallery/gal1/12.png'),
  13: require('../images/gallery/gal1/13.png'),
  14: require('../images/gallery/gal1/14.png'),
}

const gal2 = {
  0: require('../images/gallery/gal2/0.png'),
  1: require('../images/gallery/gal2/1.png'),
  2: require('../images/gallery/gal2/2.png'),
  3: require('../images/gallery/gal2/3.png'),
  4: require('../images/gallery/gal2/4.png'),
  5: require('../images/gallery/gal2/5.png'),
  6: require('../images/gallery/gal2/6.png'),
  7: require('../images/gallery/gal2/7.png'),
  8: require('../images/gallery/gal2/8.png'),
  9: require('../images/gallery/gal2/9.png'),
  10: require('../images/gallery/gal2/10.png'),
  11: require('../images/gallery/gal2/11.png'),
  12: require('../images/gallery/gal2/12.png'),
  13: require('../images/gallery/gal2/13.png'),
  14: require('../images/gallery/gal2/14.png'),
}

const gal3 = {
  0: require('../images/gallery/gal3/0.png'),
  1: require('../images/gallery/gal3/1.png'),
  2: require('../images/gallery/gal3/2.png'),
  3: require('../images/gallery/gal3/3.png'),
  4: require('../images/gallery/gal3/4.png'),
  5: require('../images/gallery/gal3/5.png'),
  6: require('../images/gallery/gal3/6.png'),
  7: require('../images/gallery/gal3/7.png'),
  8: require('../images/gallery/gal3/8.png'),
  9: require('../images/gallery/gal3/9.png'),
  10: require('../images/gallery/gal3/10.png'),
  11: require('../images/gallery/gal3/11.png'),
  12: require('../images/gallery/gal3/12.png'),
  13: require('../images/gallery/gal3/13.png'),
  14: require('../images/gallery/gal3/14.png'),
}


const gal4 = {
  0: require('../images/gallery/gal4/0.png'),
  1: require('../images/gallery/gal4/1.png'),
  2: require('../images/gallery/gal4/2.png'),
  3: require('../images/gallery/gal4/3.png'),
  4: require('../images/gallery/gal4/4.png'),
  5: require('../images/gallery/gal4/5.png'),
  6: require('../images/gallery/gal4/6.png'),
  7: require('../images/gallery/gal4/7.png'),
  8: require('../images/gallery/gal4/8.png'),
  9: require('../images/gallery/gal4/9.png'),
  10: require('../images/gallery/gal4/10.png'),
  11: require('../images/gallery/gal4/11.png'),
  12: require('../images/gallery/gal4/12.png'),
  13: require('../images/gallery/gal4/13.png'),
  14: require('../images/gallery/gal4/14.png'),
}

const gal5 = {
  0: require('../images/gallery/gal5/0.png'),
  1: require('../images/gallery/gal5/1.png'),
  2: require('../images/gallery/gal5/2.png'),
  3: require('../images/gallery/gal5/3.png'),
  4: require('../images/gallery/gal5/4.png'),
  5: require('../images/gallery/gal5/5.png'),
  6: require('../images/gallery/gal5/6.png'),
  7: require('../images/gallery/gal5/7.png'),
  8: require('../images/gallery/gal5/8.png'),
  9: require('../images/gallery/gal5/9.png'),
  10: require('../images/gallery/gal5/10.png'),
  11: require('../images/gallery/gal5/11.png'),
  12: require('../images/gallery/gal5/12.png'),
  13: require('../images/gallery/gal5/13.png'),
  14: require('../images/gallery/gal5/14.png'),
}

const gal6 = {
  0: require('../images/gallery/gal6/0.png'),
  1: require('../images/gallery/gal6/1.png'),
  2: require('../images/gallery/gal6/2.png'),
  3: require('../images/gallery/gal6/3.png'),
  4: require('../images/gallery/gal6/4.png'),
  5: require('../images/gallery/gal6/5.png'),
  6: require('../images/gallery/gal6/6.png'),
  7: require('../images/gallery/gal6/7.png'),
  8: require('../images/gallery/gal6/8.png'),
  9: require('../images/gallery/gal6/9.png'),
  10: require('../images/gallery/gal6/10.png'),
  11: require('../images/gallery/gal6/11.png'),
  12: require('../images/gallery/gal6/12.png'),
  13: require('../images/gallery/gal6/13.png'),
  14: require('../images/gallery/gal6/14.png'),
}

const gal7 = {
  0: require('../images/gallery/gal7/0.png'),
  1: require('../images/gallery/gal7/1.png'),
  2: require('../images/gallery/gal7/2.png'),
  3: require('../images/gallery/gal7/3.png'),
  4: require('../images/gallery/gal7/4.png'),
  5: require('../images/gallery/gal7/5.png'),
  6: require('../images/gallery/gal7/6.png'),
  7: require('../images/gallery/gal7/7.png'),
  8: require('../images/gallery/gal7/8.png'),
  9: require('../images/gallery/gal7/9.png'),
  10: require('../images/gallery/gal7/10.png'),
  11: require('../images/gallery/gal7/11.png'),
  12: require('../images/gallery/gal7/12.png'),
  13: require('../images/gallery/gal7/13.png'),
  14: require('../images/gallery/gal7/14.png'),
}

const gal8 = {
  0: require('../images/gallery/gal8/0.png'),
  1: require('../images/gallery/gal8/1.png'),
  2: require('../images/gallery/gal8/2.png'),
  3: require('../images/gallery/gal8/3.png'),
  4: require('../images/gallery/gal8/4.png'),
  5: require('../images/gallery/gal8/5.png'),
  6: require('../images/gallery/gal8/6.png'),
  7: require('../images/gallery/gal8/7.png'),
  8: require('../images/gallery/gal8/8.png'),
  9: require('../images/gallery/gal8/9.png'),
  10: require('../images/gallery/gal8/10.png'),
  11: require('../images/gallery/gal8/11.png'),
  12: require('../images/gallery/gal8/12.png'),
  13: require('../images/gallery/gal8/13.png'),
  14: require('../images/gallery/gal8/14.png'),
}

const gal9 = {
  0: require('../images/gallery/gal9/0.png'),
  1: require('../images/gallery/gal9/1.png'),
  2: require('../images/gallery/gal9/2.png'),
  3: require('../images/gallery/gal9/3.png'),
  4: require('../images/gallery/gal9/4.png'),
  5: require('../images/gallery/gal9/5.png'),
  6: require('../images/gallery/gal9/6.png'),
  7: require('../images/gallery/gal9/7.png'),
  8: require('../images/gallery/gal9/8.png'),
  9: require('../images/gallery/gal9/9.png'),
  10: require('../images/gallery/gal9/10.png'),
  11: require('../images/gallery/gal9/11.png'),
  12: require('../images/gallery/gal9/12.png'),
  13: require('../images/gallery/gal9/13.png'),
  14: require('../images/gallery/gal9/14.png'),
}

const gal10 = {
  0: require('../images/gallery/gal10/0.png'),
  1: require('../images/gallery/gal10/1.png'),
  2: require('../images/gallery/gal10/2.png'),
  3: require('../images/gallery/gal10/3.png'),
  4: require('../images/gallery/gal10/4.png'),
  5: require('../images/gallery/gal10/5.png'),
  6: require('../images/gallery/gal10/6.png'),
  7: require('../images/gallery/gal10/7.png'),
  8: require('../images/gallery/gal10/8.png'),
  9: require('../images/gallery/gal10/9.png'),
  10: require('../images/gallery/gal10/10.png'),
  11: require('../images/gallery/gal10/11.png'),
  12: require('../images/gallery/gal10/12.png'),
  13: require('../images/gallery/gal10/13.png'),
  14: require('../images/gallery/gal10/14.png'),
}


const TilesList = {
  gal1,
  gal2,
  gal3,
  gal4,
  gal5,
  gal6,
  gal7,
  gal8,
  gal9,
  gal10,
}
export default TilesList
